# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build and Test
      run: xcodebuild build -scheme GithubActionSample

    - name: Test
      run: xcodebuild test -resultBundlePath GithubActionSample.xcresult -scheme GithubActionSample

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: GithubActionSample.xcresult
        path: GithubActionSample.xcresult

    # Runs a set of commands using the runners shell
    - name: Archive
      run: xcodebuild archive -archivePath GithubActionSample.xcarchive -scheme GithubActionSample

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: GithubActionSample.xcarchive
        path: GithubActionSample.xcarchive
